# Numpy 모듈 

* numpy는 과학 계산을 위한 라이브러리로서 다차원 배열을 처리하는데 필요한 기능을 제공
> * 설치 : <pre><cod>pip install numpy</code></pre> 
> * 설치 모듈 확인 : <pre><code>import numpy as np </code></pre>

In [1]:
import numpy as np 

* numpy 에서 배열은 동일한 타입의 값들을 가짐
> 용어
> * _rank_ : 배열의 차원
> * _shape_ : 각 차원의 크기를 튜플로 표시

In [2]:
# rank 1 인 배열 선언 
list1 = [10,20,30,40]
a = np.array(list1)
print ("rank 1 인 배열")
print ("shape : ", a.shape)
print ()

# rank 2 인 배열 선언
list2 = [[1,2,3],
         ['a','b','c']]
b = np.array(list2)
print ("rank 2 인 배열")
print ("shape : ", b.shape)
print ("2열 3행 데이터 : ",b[1,2])

rank 1 인 배열
shape :  (4,)

rank 2 인 배열
shape :  (2, 3)
2열 3행 데이터 :  c


* numpy 배열 생성 
> 1. zeros() : _0_을 초기값으로 설정 
> 2. ones() : _1_을 초기값으로 설정
> 3. full() :  _사용자 지정값_을 초기값으로 설정 
> 4. eye() : _1_을 배열의 대각선으로 초기값을 가지며 나머지 부분은 _0_으로 설정

In [3]:
# zeros()
a = np.zeros((2,2))
print ('- zeros() 결과 : ')
print (a)
print ()
 
a = np.ones((2,3))
print ('- ones() 결과 : ')
print (a)
print ()
 
a = np.full((2,3), 5)
print ('- full() 결과 : ')
print (a)
print ()
 
a = np.eye(3)
print ('- eye() 결과 : ')
print (a)
print ()
 
a = np.array(range(20)).reshape((4,5))
print ('- 배열 shape 변환 결과 : ')
print (a)

- zeros() 결과 : 
[[0. 0.]
 [0. 0.]]

- ones() 결과 : 
[[1. 1. 1.]
 [1. 1. 1.]]

- full() 결과 : 
[[5 5 5]
 [5 5 5]]

- eye() 결과 : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

- 배열 shape 변환 결과 : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


* numpy 슬라이싱 

In [4]:
lst = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
arr = np.array(lst)
 
# 슬라이싱 1
a = arr[0:2, 0:2]
print ('- arr[0:2, 0:2] 결과 ')
print (a)
print ()

# 슬라이싱 2 
a = arr[1:, 1:]
print (' - arr[1:, 1:] 결과 ')
print (a)


- arr[0:2, 0:2] 결과 
[[1 2]
 [4 5]]

 - arr[1:, 1:] 결과 
[[5 6]
 [8 9]]


* numpy 정수 인덱싱 

In [5]:
lst = [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
a = np.array(lst)
 
# 정수 인덱싱
s = a[[0, 2], [1, 3]]
print (s)


[ 2 12]


* numpy 연산 
> * a + b  ==  np.add(a,b)
> * a - b  ==  np.subtract(a,b)
> * a * b  ==  np.multiply(a,b)
> * a / b  ==  np.divide(a,b)

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#print ('a shape : ',a.shape)
#print ('b shape : ',b.shape)

# 각 요소 더하기
c = a + b
# c = np.add(a, b)
print(c)  # [5 7 9]
 
# 각 요소 빼기
c = a - b
# c = np.subtract(a, b)
print(c)  # [-3 -3 -3]
 
# 각 요소 곱하기
# c = a * b
c = np.multiply(a, b)
print(c)  # [4 10 18]
 
# 각 요소 나누기
# c = a / b
c = np.divide(a, b)
print(c)  # [0.25 0.4 0.5]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


> * np.sum() : 배열요소들의 합 
> * np.prod() : 배열 요소들의 곱

In [7]:
lst1 = [
    [1,2],
    [3,4]
]
 
lst2 = [
    [5,6],
    [7,8]
]
a = np.array(lst1)
b = np.array(lst2)
 
c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]
